exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor

remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

author: Club Juvisy Juvisy

favicons:
  192: '/assets/logos/favicon-192x192.png'

timezone: Europe/Paris
encoding: utf-8
lang: fr-FR
title: Judo Club Juvisy sur Orge
logo: "/assets/logos/logo.png"
email: club.judo.juvisy+website@gmail.com
url: https://www.judo-juvisy.org
description: "Découvrez la passion du judo avec le club de Juvisy, situé dans le département de l'Essonne. Profitez de cours gratuits d'initiation et participez à des compétitions et stages passionnants. Rejoignez-nous dès aujourd'hui pour une aventure sportive et enrichissante !"
seo_description_max_words: 200

navigation_header:
  - title: Accueil
    url: /
  - title: Inscription
    url: /inscription.html
  - title: Nous contacter
    url: /contact.html
  - title: Les entraînements
    url: /entrainements.html

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap